import sys
import json
from datetime import datetime, timedelta

def main():
    try:
        # Read JSON data from stdin
        input_data = sys.stdin.read()
        if not input_data:
            print(json.dumps({"error": "No input provided"}))
            return
            
        logs = json.loads(input_data)
        
        # We need to compute:
        # 1. Heatmap Data: volume/count per day for the last 30 days
        # 2. Pie Chart Data: distribution of sets by exercise mapping to body parts
        
        # Basic mapping of exercises to body parts
        body_part_map = {
            "Bench Press": "Chest",
            "Squat": "Legs",
            "Deadlift": "Back",
            "Pull-Up": "Back",
            "Overhead Press": "Shoulders",
            "Push-Up": "Chest",
            "Plank": "Core",
            "Lunge": "Legs",
            "Bicep Curl": "Arms",
            "Tricep Extension": "Arms"
        }
        
        heatmap_data = {}
        pie_data = {}
        
        today_date_str = datetime.now().strftime('%Y-%m-%d')
        
        for log in logs:
            # log format: { exercise: 'Bench Press', sets: 3, reps: 10, weight: 60, date: '2023-10-01' }
            date_str = log.get("date", today_date_str)
            ex = log.get("exercise", "Other")
            sets = int(log.get("sets", 0))
            reps = int(log.get("reps", 0))
            weight = float(log.get("weight", 0))
            
            # Volume = sets * reps * weight
            volume = sets * reps * weight
            
            # 1. Update Heatmap
            if date_str not in heatmap_data:
                heatmap_data[date_str] = 0
            heatmap_data[date_str] += volume
            
            # 2. Update Pie Chart
            group = body_part_map.get(ex, "Other")
            if group not in pie_data:
                pie_data[group] = 0
            pie_data[group] += sets  # Count total sets per muscle group
            
        # Format heatmap specifically for Chart.js or D3 usage (list of {x: date, y: volume})
        heatmap_list = [{"date": k, "volume": v} for k, v in heatmap_data.items()]
        heatmap_list.sort(key=lambda x: x["date"])
        
        output = {
            "success": True,
            "heatmap": heatmap_list,
            "pieChart": pie_data,
            "message": "Analytics generated by Python successfully"
        }
        
        print(json.dumps(output))
        
    except Exception as e:
        print(json.dumps({"success": False, "error": str(e)}))

if __name__ == "__main__":
    main()
